dist: trusty
language: node_js
version: 1.0
node_js: stable
before_script: npm install
script:
  - npm run test
  - npm run lint
jobs:
  include:
    - stage: npm release
      node_js: stable
      before_deploy:
      - npm install
      - npm run build
      - npm version 1.0.$TRAVIS_BUILD_NUMBER
      deploy:
        skip_cleanup: true
        provider: npm
        email: "webdev@experium.ru"
        api_key: "$NPM_API_KEY"
        on:
          branch: master
